//! nayr.lock Format — Reader and Writer
//!
//! The nayr.lock format is a text-based structured format, inspired by
//! yarn.lock v1 but with cleaner key: value syntax and explicit workspace
//! metadata. It is the only format nayr writes; yarn.lock v1 is read-only.
//!
//! Format specification:
//!
//! ```
//! # nayr lockfile v1
//! # generated by nayr 0.1.0
//!
//! lodash@^4.17.0, lodash@^4.17.21:
//!   version: 4.17.21
//!   resolved: https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz
//!   integrity: sha512-v2kDEe...
//!
//! @babel/core@^7.23.0:
//!   version: 7.24.0
//!   resolved: https://registry.npmjs.org/@babel/core/-/core-7.24.0.tgz
//!   integrity: sha512-fQfkg0...
//!   dependencies:
//!     @babel/generator: ^7.24.0
//!
//! __workspaces:
//!   @luckymaker/lm:
//!     location: .bin/lm
//!     version: 1.0.0
//! ```

const std = @import("std");
const types = @import("types.zig");
const Lockfile = types.Lockfile;
const LockfileEntry = types.LockfileEntry;

// ============================================================================
// Writer
// ============================================================================

/// Serialises a `Lockfile` to the nayr.lock format and writes it to a file.
///
/// Entries are sorted lexicographically by their first pattern for
/// deterministic output.
///
/// ## Parameters
/// - `lockfile`: The lockfile to serialise.
/// - `path`: Absolute path to write (will be created or overwritten atomically).
/// - `allocator`: Scratch allocator for sorting and formatting.
pub fn writeFile(lockfile: *const Lockfile, path: []const u8, allocator: std.mem.Allocator) !void {
    // Write to a temporary file first, then atomically rename.
    const tmp_path = try std.fmt.allocPrint(allocator, "{s}.tmp", .{path});
    defer allocator.free(tmp_path);

    {
        const file = try std.fs.createFileAbsolute(tmp_path, .{ .truncate = true });
        defer file.close();
        const w = file.writer();

        try w.writeAll("# nayr lockfile v1\n");
        try w.print("# generated by nayr 0.1.0\n\n", .{});

        // Sort entries by first pattern for deterministic output.
        var sorted = try allocator.alloc(*const LockfileEntry, lockfile.entries.len);
        defer allocator.free(sorted);
        for (lockfile.entries, 0..) |*e, i| sorted[i] = e;
        std.mem.sort(*const LockfileEntry, sorted, {}, entryLt);

        for (sorted) |entry| {
            // Header: all patterns joined by ", ".
            for (entry.patterns, 0..) |pat, i| {
                if (i > 0) try w.writeAll(", ");
                try w.writeAll(pat);
            }
            try w.writeAll(":\n");

            try w.print("  version: {s}\n", .{entry.version});
            if (entry.resolved.len > 0) try w.print("  resolved: {s}\n", .{entry.resolved});
            if (entry.integrity.len > 0) try w.print("  integrity: {s}\n", .{entry.integrity});

            if (entry.dependencies.count() > 0) {
                try w.writeAll("  dependencies:\n");
                var it = entry.dependencies.iterator();
                while (it.next()) |kv| {
                    try w.print("    {s}: {s}\n", .{ kv.key_ptr.*, kv.value_ptr.* });
                }
            }

            if (entry.optional_dependencies.count() > 0) {
                try w.writeAll("  optionalDependencies:\n");
                var it = entry.optional_dependencies.iterator();
                while (it.next()) |kv| {
                    try w.print("    {s}: {s}\n", .{ kv.key_ptr.*, kv.value_ptr.* });
                }
            }

            try w.writeAll("\n");
        }

        // Workspace section.
        if (lockfile.workspaces.count() > 0) {
            try w.writeAll("__workspaces:\n");
            var it = lockfile.workspaces.iterator();
            while (it.next()) |kv| {
                try w.print("  {s}:\n", .{kv.key_ptr.*});
                try w.print("    location: {s}\n", .{kv.value_ptr.*.location});
                try w.print("    version: {s}\n", .{kv.value_ptr.*.version});
            }
        }
    }

    // Atomic rename: readers never see a partial file.
    try std.fs.renameAbsolute(tmp_path, path);
}

// ============================================================================
// Reader
// ============================================================================

/// Parses a nayr.lock file from the given path.
///
/// ## Parameters
/// - `allocator`: All strings and maps are allocated here.
/// - `path`: Absolute path to the nayr.lock file.
pub fn parseFile(allocator: std.mem.Allocator, path: []const u8) !Lockfile {
    const file = std.fs.openFileAbsolute(path, .{}) catch |err| {
        if (err == error.FileNotFound) return Lockfile.init();
        return err;
    };
    defer file.close();
    const contents = try file.readToEndAlloc(allocator, 32 * 1024 * 1024);
    defer allocator.free(contents);
    return parseSlice(allocator, contents);
}

/// Parses a nayr.lock from an in-memory byte slice.
pub fn parseSlice(allocator: std.mem.Allocator, src: []const u8) !Lockfile {
    if (!std.mem.startsWith(u8, src, "# nayr lockfile v1")) {
        return error.NotNayrLockfile;
    }

    var entries = std.ArrayList(LockfileEntry).init(allocator);
    var pattern_map = std.StringHashMapUnmanaged(usize){};
    var workspaces = std.StringHashMapUnmanaged(Lockfile.WorkspaceInfo){};

    var parser = NayrParser{ .src = src, .pos = 0, .allocator = allocator };

    while (!parser.atEnd()) {
        parser.skipBlankAndComment();
        if (parser.atEnd()) break;

        // __workspaces section.
        if (std.mem.startsWith(u8, parser.src[parser.pos..], "__workspaces:")) {
            parser.skipToEndOfLine();
            try parser.parseWorkspaces(&workspaces);
            continue;
        }

        // Regular entry.
        const entry = parser.parseEntry() catch {
            parser.skipToEndOfLine();
            continue;
        };

        const idx = entries.items.len;
        for (entry.patterns) |pat| {
            try pattern_map.put(allocator, pat, idx);
        }
        try entries.append(entry);
    }

    return Lockfile{
        .pattern_map = pattern_map,
        .entries = try entries.toOwnedSlice(),
        .workspaces = workspaces,
    };
}

// ============================================================================
// Internal parser
// ============================================================================

const NayrParser = struct {
    src: []const u8,
    pos: usize,
    allocator: std.mem.Allocator,

    fn atEnd(self: *const NayrParser) bool {
        return self.pos >= self.src.len;
    }

    fn skipToEndOfLine(self: *NayrParser) void {
        while (self.pos < self.src.len and self.src[self.pos] != '\n') self.pos += 1;
        if (self.pos < self.src.len) self.pos += 1;
    }

    fn skipBlankAndComment(self: *NayrParser) void {
        while (self.pos < self.src.len) {
            const c = self.src[self.pos];
            if (c == '\n' or c == '\r') {
                self.pos += 1;
            } else if (c == '#') {
                self.skipToEndOfLine();
            } else {
                break;
            }
        }
    }

    fn indentLevel(self: *const NayrParser) usize {
        var i = self.pos;
        var n: usize = 0;
        while (i < self.src.len and self.src[i] == ' ') : (i += 1) n += 1;
        return n;
    }

    fn parseEntry(self: *NayrParser) !LockfileEntry {
        const patterns = try self.parsePatternHeader();
        var entry = LockfileEntry{ .patterns = patterns, .version = "" };

        while (!self.atEnd()) {
            const indent = self.indentLevel();
            if (indent == 0) break;
            self.pos += indent;

            const key = self.readUntil(':');
            if (self.pos < self.src.len) self.pos += 1; // skip ':'

            self.skipInlineSpace();

            if (std.mem.eql(u8, key, "version")) {
                entry.version = try self.allocator.dupe(u8, self.readUntilEol());
            } else if (std.mem.eql(u8, key, "resolved")) {
                entry.resolved = try self.allocator.dupe(u8, self.readUntilEol());
            } else if (std.mem.eql(u8, key, "integrity")) {
                entry.integrity = try self.allocator.dupe(u8, self.readUntilEol());
            } else if (std.mem.eql(u8, key, "dependencies")) {
                self.skipToEndOfLine();
                try self.parseDeps(&entry.dependencies, indent + 2);
                continue;
            } else if (std.mem.eql(u8, key, "optionalDependencies")) {
                self.skipToEndOfLine();
                try self.parseDeps(&entry.optional_dependencies, indent + 2);
                continue;
            }
            self.skipToEndOfLine();
        }

        return entry;
    }

    fn parsePatternHeader(self: *NayrParser) ![]const []const u8 {
        var pats = std.ArrayList([]const u8).init(self.allocator);
        while (!self.atEnd() and self.src[self.pos] != ':' and self.src[self.pos] != '\n') {
            self.skipInlineSpace();
            const tok = self.readUntilAny(&[_]u8{ ',', ':', '\n' });
            const trimmed = std.mem.trim(u8, tok, " \t");
            if (trimmed.len > 0) try pats.append(try self.allocator.dupe(u8, trimmed));
            if (!self.atEnd() and self.src[self.pos] == ',') self.pos += 1;
        }
        if (!self.atEnd() and self.src[self.pos] == ':') self.pos += 1;
        self.skipToEndOfLine();
        return pats.toOwnedSlice();
    }

    fn parseDeps(self: *NayrParser, map: *std.StringHashMapUnmanaged([]const u8), expected_indent: usize) !void {
        while (!self.atEnd()) {
            const indent = self.indentLevel();
            if (indent < expected_indent) break;
            self.pos += indent;
            const key = try self.allocator.dupe(u8, self.readUntil(':'));
            if (self.pos < self.src.len) self.pos += 1;
            self.skipInlineSpace();
            const val = try self.allocator.dupe(u8, self.readUntilEol());
            try map.put(self.allocator, key, val);
            self.skipToEndOfLine();
        }
    }

    fn parseWorkspaces(self: *NayrParser, map: *std.StringHashMapUnmanaged(Lockfile.WorkspaceInfo)) !void {
        while (!self.atEnd()) {
            const indent = self.indentLevel();
            if (indent < 2) break;
            self.pos += indent;
            const name = try self.allocator.dupe(u8, self.readUntil(':'));
            if (self.pos < self.src.len) self.pos += 1;
            self.skipToEndOfLine();

            var location: []const u8 = "";
            var version: []const u8 = "";

            // Parse nested fields.
            while (!self.atEnd()) {
                const sub_indent = self.indentLevel();
                if (sub_indent <= indent) break;
                self.pos += sub_indent;
                const key = self.readUntil(':');
                if (self.pos < self.src.len) self.pos += 1;
                self.skipInlineSpace();
                const val = self.readUntilEol();
                if (std.mem.eql(u8, key, "location")) location = try self.allocator.dupe(u8, val);
                if (std.mem.eql(u8, key, "version")) version = try self.allocator.dupe(u8, val);
                self.skipToEndOfLine();
            }

            try map.put(self.allocator, name, .{ .location = location, .version = version });
        }
    }

    fn readUntil(self: *NayrParser, stop: u8) []const u8 {
        const start = self.pos;
        while (self.pos < self.src.len and self.src[self.pos] != stop and self.src[self.pos] != '\n') self.pos += 1;
        return self.src[start..self.pos];
    }

    fn readUntilAny(self: *NayrParser, stops: []const u8) []const u8 {
        const start = self.pos;
        while (self.pos < self.src.len) {
            for (stops) |s| if (self.src[self.pos] == s) return self.src[start..self.pos];
            self.pos += 1;
        }
        return self.src[start..self.pos];
    }

    fn readUntilEol(self: *NayrParser) []const u8 {
        const start = self.pos;
        while (self.pos < self.src.len and self.src[self.pos] != '\n' and self.src[self.pos] != '\r') self.pos += 1;
        return std.mem.trimRight(u8, self.src[start..self.pos], " \t");
    }

    fn skipInlineSpace(self: *NayrParser) void {
        while (self.pos < self.src.len and (self.src[self.pos] == ' ' or self.src[self.pos] == '\t')) self.pos += 1;
    }
};

// ============================================================================
// Sorting helper
// ============================================================================

fn entryLt(_: void, a: *const LockfileEntry, b: *const LockfileEntry) bool {
    const a_pat = if (a.patterns.len > 0) a.patterns[0] else "";
    const b_pat = if (b.patterns.len > 0) b.patterns[0] else "";
    return std.mem.lessThan(u8, a_pat, b_pat);
}
